import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

def generate_cartesian_heatmap(csv_path, title='Cartesian Heatmap'):
    # Load data from CSV
    data = pd.read_csv(csv_path)

    # Create the plot
    plt.figure(figsize=(10, 8))
    sns.kdeplot(
        x=data['x'],
        y=data['y'],
        cmap='inferno',
        fill=True,
        alpha=0.6,
        thresh=0.05,
        levels=100
    )
    plt.title(title)
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.gca().invert_yaxis()  # Invert Y-axis to match screen coordinates
    plt.grid(True)
    plt.show()

if __name__ == "__main__":
    csv_path = 'generated_mockup_data.csv'  # Use the CSV generated by eye_tracker.py
    generate_cartesian_heatmap(csv_path)

